language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
- docker

jobs:
  include:
  - script: docker run openjdk:8-jdk-slim /bin/sh -c "apt-get update && apt-get install --yes git && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd JavaHamcrest && ./gradlew clean build javadoc"
  - script: docker run openjdk:9-jdk-slim /bin/sh -c "apt-get update && apt-get install --yes git && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd JavaHamcrest && ./gradlew clean build javadoc"
  - script: docker run openjdk:11-jdk-slim /bin/sh -c "apt-get update && apt-get install --yes git && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd JavaHamcrest && ./gradlew clean build javadoc"
    # use Docker in order to avoid delay of release of JDKs and availability in Travis CI
